spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
    username: root
    password:
  sql:
    init:
    mode: never
    encoding: utf-8
    continue-on-error: false
    data-locations: classpath:sample-data.sql